
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hero(object):
    def setupUi(self, hero):
        hero.setObjectName("hero")
        hero.resize(1576, 855)
        self.centralwidget = QtWidgets.QWidget(hero)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(650, 10, 911, 831))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(20, 30, 411, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 10, 311, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.splitter_4 = QtWidgets.QSplitter(self.frame)
        self.splitter_4.setGeometry(QtCore.QRect(20, 40, 361, 71))
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter = QtWidgets.QSplitter(self.splitter_4)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_5 = QtWidgets.QLabel(self.splitter)
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit.setObjectName("lineEdit")
        self.label_6 = QtWidgets.QLabel(self.splitter)
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_7 = QtWidgets.QLabel(self.splitter_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(self.splitter_2)
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.splitter_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_9 = QtWidgets.QLabel(self.splitter_3)
        self.label_9.setObjectName("label_9")
        self.comboBox = QtWidgets.QComboBox(self.splitter_3)
        self.comboBox.setObjectName("comboBox")
        self.label_10 = QtWidgets.QLabel(self.splitter_3)
        self.label_10.setObjectName("label_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.splitter_3)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(20, 180, 411, 151))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(100, 0, 171, 21))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.frame_13 = QtWidgets.QFrame(self.frame_2)
        self.frame_13.setGeometry(QtCore.QRect(9, 30, 391, 111))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(440, 30, 441, 301))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(100, 10, 211, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setGeometry(QtCore.QRect(10, 39, 421, 101))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_15 = QtWidgets.QLabel(self.frame_7)
        self.label_15.setGeometry(QtCore.QRect(160, 0, 91, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setGeometry(QtCore.QRect(9, 149, 421, 141))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_16 = QtWidgets.QLabel(self.frame_8)
        self.label_16.setGeometry(QtCore.QRect(150, 0, 121, 21))
        self.label_16.setTextFormat(QtCore.Qt.RichText)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(20, 340, 411, 301))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(70, 0, 241, 21))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(10, 30, 391, 111))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        self.label_17.setGeometry(QtCore.QRect(100, 0, 141, 21))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(10, 160, 391, 121))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_18 = QtWidgets.QLabel(self.frame_6)
        self.label_18.setGeometry(QtCore.QRect(100, 0, 151, 21))
        self.label_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.frame_9 = QtWidgets.QFrame(self.tab)
        self.frame_9.setGeometry(QtCore.QRect(440, 340, 441, 301))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_14 = QtWidgets.QLabel(self.frame_9)
        self.label_14.setGeometry(QtCore.QRect(60, 0, 301, 31))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setGeometry(QtCore.QRect(10, 30, 421, 80))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_19 = QtWidgets.QLabel(self.frame_10)
        self.label_19.setGeometry(QtCore.QRect(120, 0, 151, 20))
        self.label_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.frame_11 = QtWidgets.QFrame(self.frame_9)
        self.frame_11.setGeometry(QtCore.QRect(10, 120, 421, 80))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_20 = QtWidgets.QLabel(self.frame_11)
        self.label_20.setGeometry(QtCore.QRect(170, 0, 58, 16))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.frame_12 = QtWidgets.QFrame(self.frame_9)
        self.frame_12.setGeometry(QtCore.QRect(10, 210, 421, 80))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_21 = QtWidgets.QLabel(self.frame_12)
        self.label_21.setGeometry(QtCore.QRect(160, 0, 91, 16))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.frame_14 = QtWidgets.QFrame(self.tab)
        self.frame_14.setGeometry(QtCore.QRect(20, 680, 411, 111))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_14)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 0, 341, 24))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 0, 41, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_15 = QtWidgets.QFrame(self.tab)
        self.frame_15.setGeometry(QtCore.QRect(440, 680, 441, 111))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_15)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 0, 371, 24))
        self.comboBox_3.setObjectName("comboBox_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 0, 41, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(310, 650, 231, 31))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_16 = QtWidgets.QFrame(self.tab_3)
        self.frame_16.setGeometry(QtCore.QRect(260, 140, 361, 451))
        self.frame_16.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label = QtWidgets.QLabel(self.frame_16)
        self.label.setGeometry(QtCore.QRect(19, 20, 321, 391))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.splitter_5 = QtWidgets.QSplitter(self.frame_16)
        self.splitter_5.setGeometry(QtCore.QRect(20, 410, 331, 26))
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_2 = QtWidgets.QLabel(self.splitter_5)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.toolButton = QtWidgets.QToolButton(self.splitter_5)
        self.toolButton.setObjectName("toolButton")
        self.frame_17 = QtWidgets.QFrame(self.tab_3)
        self.frame_17.setGeometry(QtCore.QRect(20, 250, 231, 261))
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_3 = QtWidgets.QLabel(self.frame_17)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 211, 201))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.splitter_6 = QtWidgets.QSplitter(self.frame_17)
        self.splitter_6.setGeometry(QtCore.QRect(10, 230, 201, 26))
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.label_23 = QtWidgets.QLabel(self.splitter_6)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.toolButton_2 = QtWidgets.QToolButton(self.splitter_6)
        self.toolButton_2.setObjectName("toolButton_2")
        self.frame_18 = QtWidgets.QFrame(self.tab_3)
        self.frame_18.setGeometry(QtCore.QRect(340, 600, 201, 171))
        self.frame_18.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_24 = QtWidgets.QLabel(self.frame_18)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 181, 121))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.splitter_7 = QtWidgets.QSplitter(self.frame_18)
        self.splitter_7.setGeometry(QtCore.QRect(10, 130, 181, 26))
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.label_25 = QtWidgets.QLabel(self.splitter_7)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.toolButton_3 = QtWidgets.QToolButton(self.splitter_7)
        self.toolButton_3.setObjectName("toolButton_3")
        self.frame_19 = QtWidgets.QFrame(self.tab_3)
        self.frame_19.setGeometry(QtCore.QRect(630, 250, 241, 261))
        self.frame_19.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.label_26 = QtWidgets.QLabel(self.frame_19)
        self.label_26.setGeometry(QtCore.QRect(17, 20, 211, 191))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.splitter_8 = QtWidgets.QSplitter(self.frame_19)
        self.splitter_8.setGeometry(QtCore.QRect(10, 230, 221, 26))
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.label_27 = QtWidgets.QLabel(self.splitter_8)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.toolButton_4 = QtWidgets.QToolButton(self.splitter_8)
        self.toolButton_4.setObjectName("toolButton_4")
        self.frame_20 = QtWidgets.QFrame(self.tab_3)
        self.frame_20.setGeometry(QtCore.QRect(350, 10, 181, 121))
        self.frame_20.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.label_28 = QtWidgets.QLabel(self.frame_20)
        self.label_28.setGeometry(QtCore.QRect(10, 10, 161, 81))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.splitter_9 = QtWidgets.QSplitter(self.frame_20)
        self.splitter_9.setGeometry(QtCore.QRect(10, 90, 161, 26))
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.label_29 = QtWidgets.QLabel(self.splitter_9)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.toolButton_5 = QtWidgets.QToolButton(self.splitter_9)
        self.toolButton_5.setObjectName("toolButton_5")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 70, 41, 41))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 120, 41, 41))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(20, 29, 551, 791))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        hero.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(hero)
        self.statusbar.setObjectName("statusbar")
        hero.setStatusBar(self.statusbar)

        self.retranslateUi(hero)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(hero)

    def retranslateUi(self, hero):
        _translate = QtCore.QCoreApplication.translate
        hero.setWindowTitle(_translate("hero", "MainWindow"))
        self.label_4.setText(_translate("hero", "<html><head/><body><p><span style=\" font-size:14pt;\">Основная информация персонажа</span></p></body></html>"))
        self.label_5.setText(_translate("hero", "Имя"))
        self.label_6.setText(_translate("hero", "Уровень "))
        self.label_7.setText(_translate("hero", "$"))
        self.label_8.setText(_translate("hero", "Очки опыта"))
        self.label_9.setText(_translate("hero", "Кость"))
        self.label_10.setText(_translate("hero", "Карма"))
        self.label_11.setText(_translate("hero", "<html><head/><body><p><span style=\" font-size:14pt;\">Характеристики</span></p></body></html>"))
        self.label_12.setText(_translate("hero", "<html><head/><body><p><span style=\" font-size:14pt;\">Здоровье и Энергия</span></p></body></html>"))
        self.label_15.setText(_translate("hero", "<html><head/><body><p><span style=\" font-size:12pt;\">Здоровье</span></p></body></html>"))
        self.label_16.setText(_translate("hero", "<html><head/><body><p><span style=\" font-size:12pt;\">Энергия</span></p></body></html>"))
        self.label_13.setText(_translate("hero", "<html><head/><body><p><span style=\" font-size:14pt;\">Скорость и Инициатива</span></p></body></html>"))
        self.label_17.setText(_translate("hero", "<html><head/><body><p><span style=\" font-size:12pt;\">Скорость</span></p></body></html>"))
        self.label_18.setText(_translate("hero", "<html><head/><body><p><span style=\" font-size:12pt;\">Инициатива</span></p></body></html>"))
        self.label_14.setText(_translate("hero", "<html><head/><body><p><span style=\" font-size:14pt;\">Виды сопротивлений</span></p></body></html>"))
        self.label_19.setText(_translate("hero", "Стойкость"))
        self.label_20.setText(_translate("hero", "Реакция"))
        self.label_21.setText(_translate("hero", "Сознание"))
        self.pushButton_2.setText(_translate("hero", "+"))
        self.pushButton_3.setText(_translate("hero", "+"))
        self.label_22.setText(_translate("hero", "<html><head/><body><p><span style=\" font-size:14pt;\">Навыки персонажа :</span></p><p><br/></p><p><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("hero", "Tab 1"))
        self.label.setText(_translate("hero", "TextLabel"))
        self.label_2.setText(_translate("hero", "TextLabel"))
        self.toolButton.setText(_translate("hero", "..."))
        self.label_3.setText(_translate("hero", "TextLabel"))
        self.label_23.setText(_translate("hero", "TextLabel"))
        self.toolButton_2.setText(_translate("hero", "..."))
        self.label_24.setText(_translate("hero", "TextLabel"))
        self.label_25.setText(_translate("hero", "TextLabel"))
        self.toolButton_3.setText(_translate("hero", "..."))
        self.label_26.setText(_translate("hero", "TextLabel"))
        self.label_27.setText(_translate("hero", "TextLabel"))
        self.toolButton_4.setText(_translate("hero", "..."))
        self.label_28.setText(_translate("hero", "TextLabel"))
        self.label_29.setText(_translate("hero", "TextLabel"))
        self.toolButton_5.setText(_translate("hero", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("hero", "Страница"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("hero", "Tab 2"))
        self.label_30.setText(_translate("hero", "TextLabel"))